title: "oseph.Note"
description: "Joseph 의 개인 기술 노트"
baseurl: "" # 서브 디렉토리에 올릴 경우만 변경
url: "https://jxlove2020.github.io"

# Minimal Mistakes 테마 적용
remote_theme: "mmistakes/minimal-mistakes"

# GitHub Pages 호환성
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

paginate: 5
paginate_path: /page:num/

# GA
google_analytics: UA-220530722-1

# Markdown
markdown: kramdown

# 테마 세부 설정
theme_settings:
  locale: "ko-KR"
